### Hello
GET http://localhost:3000/

### Health
GET http://localhost:3000/health

### Health DB
GET http://localhost:3000/health/db

### Listar libros
GET http://localhost:3000/libros

### Libros disponibles
GET http://localhost:3000/libros?disponible=true

### Listar autores
GET http://localhost:3000/autores
